### ISSUE TITLE
Which 3D Visualization Tool/Code Do You use?

### ISSUE THREAD

**Issue by meijie0401** [dariopavllo/convmesh#5]
I'm wondering which visualization tool/code do you use to show those 3D textured meshes in this repo and in the paper? Could you please provide some sources/code/link? Thanks!!!

**Comment by dariopavllo** [comment]
Most of the visualizations in the paper/repo were rendered using the script itself (e.g. you can modify the code that exports results to Tensorboard). In the repo you can also find the wireframe texture that was used to render the wireframe meshes: https://github.com/dariopavllo/convmesh/blob/master/mesh_templates/wireframe_16rings.png
Tips: render on a white background and at a higher resolution (e.g. 1024x1024 instead of 256x256), then resize the image to 256x256 for anti-aliasing.

Alternatively, you can export the generated meshes as .obj files and open/render them with Blender. The instructions are in the readme.

**Comment by dariopavllo** [comment]
I was not aware of that feature of Tensorboard. For our visualizations during training, we simply render the meshes from random viewpoints using the renderer. This is done in the function that computes the FID.

It looks like that TensorBoard function doesn't support textures, only vertex colors. This might result in blurry results.
